"""
Reward profiles for configuring domain weights and behavioral biases.
"""

from .base import RewardProfile
from .static_profiles import (
    # Original 5 profiles
    REFLECTIVE_PROFILE,
    EXPLORATORY_SANDBOX_PROFILE,
    ETHICS_TRAINING_PROFILE,
    CREATIVE_SANDBOX_PROFILE,
    ANALYSIS_PROFILE,
    # 12 purpose-built profiles (Session 32)
    RECEPTIVE_LEARNING_PROFILE,
    CRITICAL_REVIEW_PROFILE,
    DIALECTIC_EXPLORATION_PROFILE,
    CURIOSITY_DRIVEN_PROFILE,
    AUTONOMOUS_STUDY_PROFILE,
    HOMEWORK_PROCESSING_PROFILE,
    REFLECTIVE_SYNTHESIS_PROFILE,
    SLEEP_TRIAGE_PROFILE,
    SLEEP_DEEP_PROFILE,
    SLEEP_DREAM_PROFILE,
    REGULAR_INPUT_PROFILE,
    SELF_REFLECTIVE_PROFILE,
    # Registry and default
    STATIC_PROFILES,
    PROFILE_REGISTRY,
    DEFAULT_PROFILE,
)

__all__ = [
    "RewardProfile",
    # Original 5
    "REFLECTIVE_PROFILE",
    "EXPLORATORY_SANDBOX_PROFILE",
    "ETHICS_TRAINING_PROFILE",
    "CREATIVE_SANDBOX_PROFILE",
    "ANALYSIS_PROFILE",
    # 12 purpose-built
    "RECEPTIVE_LEARNING_PROFILE",
    "CRITICAL_REVIEW_PROFILE",
    "DIALECTIC_EXPLORATION_PROFILE",
    "CURIOSITY_DRIVEN_PROFILE",
    "AUTONOMOUS_STUDY_PROFILE",
    "HOMEWORK_PROCESSING_PROFILE",
    "REFLECTIVE_SYNTHESIS_PROFILE",
    "SLEEP_TRIAGE_PROFILE",
    "SLEEP_DEEP_PROFILE",
    "SLEEP_DREAM_PROFILE",
    "REGULAR_INPUT_PROFILE",
    "SELF_REFLECTIVE_PROFILE",
    # Registry and default
    "STATIC_PROFILES",
    "PROFILE_REGISTRY",
    "DEFAULT_PROFILE",
]
